### ISSUE TITLE
Fails to start on Fedora Kinoite 38

### ISSUE THREAD

**Issue by fivezeroes** [vagnum08/cpupower-gui#107]
**Describe the bug**
Fails to launch on Fedora Kinoite 38, seems to be an identical error to #42 

```
Traceback (most recent call last):
  File "/usr/lib64/python3.11/site-packages/dbus/bus.py", line 173, in activate_name_owner
    return self.get_name_owner(bus_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/dbus/bus.py", line 348, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/dbus/connection.py", line 634, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: The name does not have an owner

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/cpupower-gui", line 33, in <module>
    from cpupower_gui.helper import (
  File "/usr/share/cpupower-gui/cpupower_gui/helper.py", line 16, in <module>
    SESSION = BUS.get_object(
              ^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/dbus/bus.py", line 237, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/dbus/bus.py", line 178, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib64/python3.11/site-packages/dbus/bus.py", line 273, in start_service_by_name
    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/dbus/connection.py", line 634, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: Could not activate remote peer: activation request failed: unknown unit.
```

**Setup (please complete the following information):**
 - Distro: Fedora Kinoite 38.20230728.0
 - Package version: cpupower-gui-1.0.0+git.21.80e68e9-1.1.noarch
 - Installed via: rpm-ostree and OBS

**Comment by vagnum08** [comment]
I will try to replicate the issue and see what really is going on.
From the message above is looks as if there is something wrong with D-Bus service activation.
When you launch the app it will try to start the system service that applies the changes via D-Bus but something is going on and it cannot start the service.

**Comment by jayv** [comment]
I get the same error since I've upgraded to Ubuntu 23.04 from 22.04 (also when I build from source)

**Comment by christophehenry** [comment]
I'm having this problem too which is unfortunate since I use cpupower to prevent my CPU from overheating. Can you tell me what I can do to debug?

**Comment by careca1970** [comment]
Hi, since long time yet, many updates, I have been having similar problems with an installation from Fedora repo.

The solution has been just uninstalling and reinstalling.

Here are the messages I got, when starting it from command line, just after upgrading (and problems arose):

```
$ cpupower-gui 
Traceback (most recent call last):
  File "/usr/lib64/python3.11/site-packages/dbus/bus.py", line 173, in activate_name_owner
    return self.get_name_owner(bus_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/dbus/bus.py", line 348, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/dbus/connection.py", line 634, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: The name does not have an owner

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/cpupower-gui", line 33, in <module>
    from cpupower_gui.helper import (
  File "/usr/share/cpupower-gui/cpupower_gui/helper.py", line 16, in <module>
    SESSION = BUS.get_object(
              ^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/dbus/bus.py", line 237, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/dbus/bus.py", line 178, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib64/python3.11/site-packages/dbus/bus.py", line 273, in start_service_by_name
    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/dbus/connection.py", line 634, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: Could not activate remote peer: activation request failed: unknown unit.
```

After "re-installation" stating at command line will result in no massages at all.

Hope it can be helpful!

**Comment by christophehenry** [comment]
Indeed, that worked. Si there's something in the RPM script that create the DBus channel. Maybe cpupower-gui should ensure itself that trhe DBus channel exists when it starts?
