### ISSUE TITLE
Permissions missing on Arch Linux

### ISSUE THREAD

**Issue by Akinevz** [vagnum08/cpupower-gui#11]
**Describe the bug**
The application appears to not be getting permissions through dbus

**To Reproduce**
1. Start application from terminal
2. Change settings
3. Apply

**Expected behaviour**
Governor and frequencies updated

**Setup (please complete the following information):**
Currently have installed
 - Distro: arch linux - 5.4.2 
 - Installed via: [package]
 - Package version: 0.7.2.r9
 - Deps:
python-dbus - 1.2.14-1

**Additional context**
```
$ cpupower-gui

(cpupower-gui:23309): IBUS-WARNING **: 12:11:06.025: Unable to connect to ibus: Could not connect: Connection refused
Traceback (most recent call last):
  File "/usr/share/cpupower-gui/cpupower_gui/window.py", line 227, in on_apply_clicked
    "You don't have permissions to update cpu settings!", self.window
AttributeError: 'CpupowerGuiWindow' object has no attribute 'window'

```

**Comment by vagnum08** [comment]
Do you get an auth window like the following after clicking apply:
![auth_win](https://user-images.githubusercontent.com/16070176/71576284-0bfb0180-2ae8-11ea-9e47-c14c487578bb.png)

Could you check with something like d-feet if the dbus helper daemon (cpupower_gui_helper) is running?
It should get launched automatically (it does if using systemd).

P.S. I tested it on Arch linux with the same dbus and cpupower-gui versions.

**Comment by vagnum08** [comment]
Closing due to inactivity. Feel free to open again if the issue persists.

**Comment by EllistonV** [comment]
Having same issue here. No other window is displayed after error message:

```
 File "/usr/share/cpupower-gui/cpupower_gui/window.py", line 221, in on_apply_clicked
    "You don't have permissions to update cpu settings!", self.window
AttributeError: 'CpupowerGuiWindow' object has no attribute 'window'
```


Running in pop_OS latest version

**Comment by vagnum08** [comment]
When you say latest you mean 22.04 right?
Which version of cpupower-gui are you running? 1.0.0 or 0.7.2 (which is included in Ubuntu repositories)

**Comment by Akinevz** [comment]
I'm not quite sure what permissions are missing, but you likely need to do `usermod -Ga` to add your user to a group that has permissions to modify/observe cpu information

**Comment by vagnum08** [comment]
The user has to be in `sudo` or `wheel` group to be able to change the settings.
