### ISSUE TITLE
cpupower-gui fails to start

### ISSUE THREAD

**Issue by panorain** [vagnum08/cpupower-gui#119]
**Describe the bug**
After upgrading to cpupower-gui Version : 1.0.0+git.24.b44a198-2.5 the application fails to execute. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Plasma start menu > settings 
2. Click on 'cpupower-gui'
3. application fails to load
4. See error in terminal below
```
Thinkcentre-M57p:~> cpupower-gui -p

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/dbus/bus.py", line 173, in activate_name_owner
    return self.get_name_owner(bus_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/bus.py", line 348, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/connection.py", line 634, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.rnd2.cpupower_gui.helper': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/cpupower-gui", line 33, in <module>
    from cpupower_gui.helper import (
  File "/usr/share/cpupower-gui/cpupower_gui/helper.py", line 16, in <module>
    SESSION = BUS.get_object(
              ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/bus.py", line 237, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/bus.py", line 178, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3.11/site-packages/dbus/bus.py", line 273, in start_service_by_name
    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/connection.py", line 634, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dbus.exceptions.DBusException: org.freedesktop.systemd1.NoSuchUnit: Unit dbus-org.rnd2.cpupower_gui.helper.service not found.


```
```
Thinkcentre-M57p:~> cpupower-gui --version

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/dbus/bus.py", line 173, in activate_name_owner
    return self.get_name_owner(bus_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/bus.py", line 348, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/connection.py", line 634, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.rnd2.cpupower_gui.helper': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/cpupower-gui", line 33, in <module>
    from cpupower_gui.helper import (
  File "/usr/share/cpupower-gui/cpupower_gui/helper.py", line 16, in <module>
    SESSION = BUS.get_object(
              ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/bus.py", line 237, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/bus.py", line 178, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3.11/site-packages/dbus/bus.py", line 273, in start_service_by_name
    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/connection.py", line 634, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dbus.exceptions.DBusException: org.freedesktop.systemd1.NoSuchUnit: Unit dbus-org.rnd2.cpupower_gui.helper.service not found.

```
**Expected behaviour**
cpupower-gui application is able to start.

**Setup (please complete the following information):**
 - Distro: openSUSE Tumbleweed 20240418, KDE Plasma 6.0.4, QT Version 6.7.0 
 - Package version: Version : 1.0.0+git.24.b44a198-2.5
 - Installed via: package https://download.opensuse.org/repositories/multimedia:proaudio/openSUSE_Tumbleweed/multimedia:proaudio.repo

**Additional context**
There are some _journalctl_ entries related to cpupower-gui also and I have added them below also.

```
Thinkcentre-M57p:~> journalctl -b -1 -r | grep -i "cpupower-gui"

Apr 19 14:09:23 Thinkcentre-M57p systemd[1]: Failed to start Apply cpupower-gui config at boot.
Apr 19 14:09:23 Thinkcentre-M57p systemd[1]: cpupower-gui.service: Failed with result 'exit-code'.
Apr 19 14:09:23 Thinkcentre-M57p systemd[1]: cpupower-gui.service: Main process exited, code=exited, status=1/FAILURE
Apr 19 14:09:23 Thinkcentre-M57p cpupower-gui[7331]: dbus.exceptions.DBusException: org.freedesktop.systemd1.NoSuchUnit: Unit dbus-org.rnd2.cpupower_gui.helper.service not found.
Apr 19 14:09:23 Thinkcentre-M57p cpupower-gui[7331]:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Apr 19 14:09:23 Thinkcentre-M57p cpupower-gui[7331]:     reply_message = self.send_message_with_reply_and_block(
Apr 19 14:09:23 Thinkcentre-M57p cpupower-gui[7331]:   File "/usr/lib/python3.11/site-packages/dbus/connection.py", line 634, in call_blocking
Apr 19 14:09:23 Thinkcentre-M57p cpupower-gui[7331]:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Apr 19 14:09:23 Thinkcentre-M57p cpupower-gui[7331]:     return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
Apr 19 14:09:23 Thinkcentre-M57p cpupower-gui[7331]:   File "/usr/lib/python3.11/site-packages/dbus/bus.py", line 273, in start_service_by_name
Apr 19 14:09:23 Thinkcentre-M57p cpupower-gui[7331]:     self.start_service_by_name(bus_name)
Apr 19 14:09:23 Thinkcentre-M57p cpupower-gui[7331]:   File "/usr/lib/python3.11/site-packages/dbus/bus.py", line 178, in activate_name_owner
Apr 19 14:09:23 Thinkcentre-M57p cpupower-gui[7331]:                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Apr 19 14:09:23 Thinkcentre-M57p cpupower-gui[7331]:     self._named_service = conn.activate_name_owner(bus_name)
Apr 19 14:09:23 Thinkcentre-M57p cpupower-gui[7331]:   File "/usr/lib/python3.11/site-packages/dbus/proxies.py", line 250, in __init__
Apr 19 14:09:23 Thinkcentre-M57p cpupower-gui[7331]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Apr 19 14:09:23 Thinkcentre-M57p cpupower-gui[7331]:     return self.ProxyObjectClass(self, bus_name, object_path,
Apr 19 14:09:23 Thinkcentre-M57p cpupower-gui[7331]:   File "/usr/lib/python3.11/site-packages/dbus/bus.py", line 237, in get_object
Apr 19 14:09:23 Thinkcentre-M57p cpupower-gui[7331]:               ^^^^^^^^^^^^^^^
Apr 19 14:09:23 Thinkcentre-M57p cpupower-gui[7331]:     SESSION = BUS.get_object(
Apr 19 14:09:23 Thinkcentre-M57p cpupower-gui[7331]:   File "/usr/share/cpupower-gui/cpupower_gui/helper.py", line 16, in <module>
Apr 19 14:09:23 Thinkcentre-M57p cpupower-gui[7331]:     from cpupower_gui.helper import (
Apr 19 14:09:23 Thinkcentre-M57p cpupower-gui[7331]:   File "/usr/bin/cpupower-gui", line 33, in <module>
Apr 19 14:09:23 Thinkcentre-M57p cpupower-gui[7331]: Traceback (most recent call last):
Apr 19 14:09:23 Thinkcentre-M57p cpupower-gui[7331]: During handling of the above exception, another exception occurred:
Apr 19 14:09:23 Thinkcentre-M57p cpupower-gui[7331]: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.rnd2.cpupower_gui.helper': no such name
Apr 19 14:09:23 Thinkcentre-M57p cpupower-gui[7331]:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Apr 19 14:09:23 Thinkcentre-M57p cpupower-gui[7331]:     reply_message = self.send_message_with_reply_and_block(
Apr 19 14:09:23 Thinkcentre-M57p cpupower-gui[7331]:   File "/usr/lib/python3.11/site-packages/dbus/connection.py", line 634, in call_blocking
Apr 19 14:09:23 Thinkcentre-M57p cpupower-gui[7331]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Apr 19 14:09:23 Thinkcentre-M57p cpupower-gui[7331]:     return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
Apr 19 14:09:23 Thinkcentre-M57p cpupower-gui[7331]:   File "/usr/lib/python3.11/site-packages/dbus/bus.py", line 348, in get_name_owner
Apr 19 14:09:23 Thinkcentre-M57p cpupower-gui[7331]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Apr 19 14:09:23 Thinkcentre-M57p cpupower-gui[7331]:     return self.get_name_owner(bus_name)
Apr 19 14:09:23 Thinkcentre-M57p cpupower-gui[7331]:   File "/usr/lib/python3.11/site-packages/dbus/bus.py", line 173, in activate_name_owner
Apr 19 14:09:23 Thinkcentre-M57p cpupower-gui[7331]: Traceback (most recent call last):
Apr 19 14:09:23 Thinkcentre-M57p dbus-daemon[1108]: [system] Activating via systemd: service name='org.rnd2.cpupower_gui.helper' unit='dbus-org.rnd2.cpupower_gui.helper.service' requested by ':1.173' (uid=0 pid=7331 comm="/usr/bin/python3 /usr/bin/cpupower-gui config")
Apr 19 14:09:22 Thinkcentre-M57p systemd[1]: Starting Apply cpupower-gui config at boot...
Apr 19 14:09:22 Thinkcentre-M57p polkitd[1145]: Operator of unix-session:3 successfully authenticated as unix-user:root to gain TEMPORARY authorization for action org.freedesktop.systemd1.manage-units for system-bus-name::1.170 [systemctl start cpupower-gui] (owned by unix-user:paul)
Apr 19 14:09:11 Thinkcentre-M57p polkitd[1145]: Operator of unix-session:3 successfully authenticated as unix-user:root to gain TEMPORARY authorization for action org.freedesktop.systemd1.manage-unit-files for system-bus-name::1.165 [systemctl enable cpupower-gui] (owned by unix-user:paul)
Apr 19 14:03:46 Thinkcentre-M57p [RPM][5259]: install cpupower-gui-1.0.0+git.24.b44a198-2.5.noarch: success
Apr 19 14:03:46 Thinkcentre-M57p [RPM][5259]: erase cpupower-gui-1.0.0+git.24.b44a198-2.5.noarch: success
Apr 19 14:03:45 Thinkcentre-M57p systemd[1]: Stopped cpupower-gui system helper.
Apr 19 14:03:45 Thinkcentre-M57p systemd[1]: cpupower-gui-helper.service: Deactivated successfully.
Apr 19 14:03:45 Thinkcentre-M57p systemd[1]: Stopping cpupower-gui system helper...
Apr 19 14:03:45 Thinkcentre-M57p [RPM][5259]: install cpupower-gui-1.0.0+git.24.b44a198-2.5.noarch: success
Apr 19 14:03:45 Thinkcentre-M57p systemd[1]: Finished Apply cpupower-gui config at boot.
Apr 19 14:03:45 Thinkcentre-M57p systemd[1]: cpupower-gui.service: Deactivated successfully.
Apr 19 14:03:45 Thinkcentre-M57p cpupower-gui[5400]:     Governor: Schedutil, Online: True
Apr 19 14:03:45 Thinkcentre-M57p cpupower-gui[5400]:     Minimum Frequency: 2000.0 MHz, Maximum Frequency: 2667.0 MHz
Apr 19 14:03:45 Thinkcentre-M57p cpupower-gui[5400]: Setting CPU: 3
Apr 19 14:03:45 Thinkcentre-M57p cpupower-gui[5400]:     Governor: Schedutil, Online: True
Apr 19 14:03:45 Thinkcentre-M57p cpupower-gui[5400]:     Minimum Frequency: 2000.0 MHz, Maximum Frequency: 2667.0 MHz
Apr 19 14:03:45 Thinkcentre-M57p cpupower-gui[5400]: Setting CPU: 2
Apr 19 14:03:45 Thinkcentre-M57p cpupower-gui[5400]:     Governor: Schedutil, Online: True
Apr 19 14:03:45 Thinkcentre-M57p cpupower-gui[5400]:     Minimum Frequency: 2000.0 MHz, Maximum Frequency: 2667.0 MHz
Apr 19 14:03:45 Thinkcentre-M57p cpupower-gui[5400]: Setting CPU: 1
Apr 19 14:03:45 Thinkcentre-M57p cpupower-gui[5400]:     Governor: Schedutil, Online: True
Apr 19 14:03:45 Thinkcentre-M57p cpupower-gui[5400]:     Minimum Frequency: 2000.0 MHz, Maximum Frequency: 2667.0 MHz
Apr 19 14:03:45 Thinkcentre-M57p cpupower-gui[5400]: Setting CPU: 0
Apr 19 14:03:45 Thinkcentre-M57p cpupower-gui[5400]: Applying configuration...
Apr 19 14:03:45 Thinkcentre-M57p systemd[1]: Started cpupower-gui system helper.
Apr 19 14:03:45 Thinkcentre-M57p dbus-daemon[1108]: [system] Activating via systemd: service name='org.rnd2.cpupower_gui.helper' unit='dbus-org.rnd2.cpupower_gui.helper.service' requested by ':1.155' (uid=0 pid=5400 comm="/usr/bin/python3 /usr/bin/cpupower-gui config")
Apr 19 14:03:44 Thinkcentre-M57p systemd[1]: Starting Apply cpupower-gui config at boot...
Apr 19 14:03:44 Thinkcentre-M57p systemd[1]: Starting cpupower-gui system helper...
Apr 19 14:03:43 Thinkcentre-M57p [RPM][5259]: erase cpupower-gui-1.0.0+git.24.b44a198-2.5.noarch: success
Apr 19 13:55:24 Thinkcentre-M57p dbus-daemon[1108]: [system] Activating via systemd: service name='org.rnd2.cpupower_gui.helper' unit='dbus-org.rnd2.cpupower_gui.helper.service' requested by ':1.118' (uid=1000 pid=4445 comm="/usr/bin/python3 /usr/bin/cpupower-gui -h")
Apr 19 13:51:36 Thinkcentre-M57p org.rnd2.cpupower_gui[4202]:   File "/usr/share/cpupower-gui/cpupower_gui/helper.py", line 16, in <module>
Apr 19 13:51:36 Thinkcentre-M57p org.rnd2.cpupower_gui[4202]:   File "/usr/bin/cpupower-gui", line 33, in <module>
Apr 19 13:51:36 Thinkcentre-M57p dbus-daemon[1108]: [system] Activating via systemd: service name='org.rnd2.cpupower_gui.helper' unit='dbus-org.rnd2.cpupower_gui.helper.service' requested by ':1.116' (uid=1000 pid=4202 comm="/usr/bin/python3 /usr/bin/cpupower-gui --gapplicat")
Apr 19 13:51:36 Thinkcentre-M57p systemd[1856]: Started cpupower-gui - CPU frequency settings.
Apr 19 13:36:46 Thinkcentre-M57p org.rnd2.cpupower_gui[3786]:   File "/usr/share/cpupower-gui/cpupower_gui/helper.py", line 16, in <module>
Apr 19 13:36:46 Thinkcentre-M57p org.rnd2.cpupower_gui[3786]:   File "/usr/bin/cpupower-gui", line 33, in <module>
Apr 19 13:36:46 Thinkcentre-M57p dbus-daemon[1108]: [system] Activating via systemd: service name='org.rnd2.cpupower_gui.helper' unit='dbus-org.rnd2.cpupower_gui.helper.service' requested by ':1.104' (uid=1000 pid=3786 comm="/usr/bin/python3 /usr/bin/cpupower-gui --gapplicat")
Apr 19 13:36:46 Thinkcentre-M57p systemd[1856]: Started cpupower-gui - CPU frequency settings.
Apr 19 13:36:17 Thinkcentre-M57p org.rnd2.cpupower_gui[3461]:   File "/usr/share/cpupower-gui/cpupower_gui/helper.py", line 16, in <module>
Apr 19 13:36:17 Thinkcentre-M57p org.rnd2.cpupower_gui[3461]:   File "/usr/bin/cpupower-gui", line 33, in <module>
Apr 19 13:36:17 Thinkcentre-M57p dbus-daemon[1108]: [system] Activating via systemd: service name='org.rnd2.cpupower_gui.helper' unit='dbus-org.rnd2.cpupower_gui.helper.service' requested by ':1.90' (uid=1000 pid=3461 comm="/usr/bin/python3 /usr/bin/cpupower-gui --gapplicat")
Apr 19 13:36:17 Thinkcentre-M57p systemd[1856]: Started cpupower-gui - CPU frequency settings.
Apr 19 13:34:09 Thinkcentre-M57p org.rnd2.cpupower_gui[3362]:   File "/usr/share/cpupower-gui/cpupower_gui/helper.py", line 16, in <module>
Apr 19 13:34:09 Thinkcentre-M57p org.rnd2.cpupower_gui[3362]:   File "/usr/bin/cpupower-gui", line 33, in <module>
Apr 19 13:34:09 Thinkcentre-M57p dbus-daemon[1108]: [system] Activating via systemd: service name='org.rnd2.cpupower_gui.helper' unit='dbus-org.rnd2.cpupower_gui.helper.service' requested by ':1.89' (uid=1000 pid=3362 comm="/usr/bin/python3 /usr/bin/cpupower-gui --gapplicat")
Apr 19 13:34:09 Thinkcentre-M57p systemd[1856]: Started cpupower-gui - CPU frequency settings.
Apr 19 13:31:50 Thinkcentre-M57p org.rnd2.cpupower_gui[3276]:   File "/usr/share/cpupower-gui/cpupower_gui/helper.py", line 16, in <module>
Apr 19 13:31:50 Thinkcentre-M57p org.rnd2.cpupower_gui[3276]:   File "/usr/bin/cpupower-gui", line 33, in <module>
Apr 19 13:31:50 Thinkcentre-M57p dbus-daemon[1108]: [system] Activating via systemd: service name='org.rnd2.cpupower_gui.helper' unit='dbus-org.rnd2.cpupower_gui.helper.service' requested by ':1.88' (uid=1000 pid=3276 comm="/usr/bin/python3 /usr/bin/cpupower-gui --gapplicat")
Apr 19 13:31:50 Thinkcentre-M57p systemd[1856]: Started cpupower-gui - CPU frequency settings.




```

SystemD service status displays as this:

 ```
Thinkcentre-M57p:~> systemctl status cpupower-gui
× cpupower-gui.service - Apply cpupower-gui config at boot
     Loaded: loaded (/usr/lib/systemd/system/cpupower-gui.service; enabled; preset: disabled)
     Active: failed (Result: exit-code) since Fri 2024-04-19 14:13:09 CDT; 52min ago
       Docs: https://github.com/vagnum08/cpupower-gui
             man:cpupower-gui(1)
    Process: 3417 ExecStart=/usr/bin/cpupower-gui config (code=exited, status=1/FAILURE)
   Main PID: 3417 (code=exited, status=1/FAILURE)
        CPU: 118ms

Apr 19 14:13:09 Thinkcentre-M57p cpupower-gui[3417]:   File "/usr/lib/python3.11/site-packages/dbus/bus.py", line 273, in start_service_by_name
Apr 19 14:13:09 Thinkcentre-M57p cpupower-gui[3417]:     return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
Apr 19 14:13:09 Thinkcentre-M57p cpupower-gui[3417]:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Apr 19 14:13:09 Thinkcentre-M57p cpupower-gui[3417]:   File "/usr/lib/python3.11/site-packages/dbus/connection.py", line 634, in call_blocking
Apr 19 14:13:09 Thinkcentre-M57p cpupower-gui[3417]:     reply_message = self.send_message_with_reply_and_block(
Apr 19 14:13:09 Thinkcentre-M57p cpupower-gui[3417]:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Apr 19 14:13:09 Thinkcentre-M57p cpupower-gui[3417]: dbus.exceptions.DBusException: org.freedesktop.systemd1.NoSuchUnit: Unit dbus-org.rnd2.cpupower_gui.helper.service not found.
Apr 19 14:13:09 Thinkcentre-M57p systemd[1]: cpupower-gui.service: Main process exited, code=exited, status=1/FAILURE
Apr 19 14:13:09 Thinkcentre-M57p systemd[1]: cpupower-gui.service: Failed with result 'exit-code'.
Apr 19 14:13:09 Thinkcentre-M57p systemd[1]: Failed to start Apply cpupower-gui config at boot.
Thinkcentre-M57p:~> 

```
I don't know what else to add to this right now if more is necessary.

-Best Wishes

**Comment by panorain** [comment]
My apologies. I had `cpupower-gui-helper.service` disabled and I believe this is the reason for it not working.
