### ISSUE TITLE
gapplication: error sending Activate message to application

### ISSUE THREAD

**Issue by TensorTom** [vagnum08/cpupower-gui#21]
Distro: Mint 19.3 (Ubuntu 18.04)
cpupower-gui: 0.8.0
system python: 3.6.9

Followed the newest build steps from README and https://github.com/vagnum08/cpupower-gui/issues/18 but it did not work. Initially got gi version error so took these steps:
```
apt install libgirepository1.0-dev gcc libcairo2-dev pkg-config python3-dev gir1.2-gtk-3.0
pip3 install pycairo --upgrade
pip3 install PyGObject --upgrade
```
This fixed the version error but cpupower-gui still will not start:
```
gapplication launch org.rnd2.cpupower_gui
error sending Activate message to application: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.rnd2.cpupower_gui exited with status 1
```
I also tried to start it directly by `/usr/bin/python3 /usr/bin/cpupower-gui` which produces:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.rnd2.cpupower_gui.helper': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/cpupower-gui", line 40, in <module>
    from cpupower_gui import main
  File "/usr/share/cpupower-gui/cpupower_gui/main.py", line 36, in <module>
    from .window import CpupowerGuiWindow
  File "/usr/share/cpupower-gui/cpupower_gui/window.py", line 26, in <module>
    "org.rnd2.cpupower_gui.helper", "/org/rnd2/cpupower_gui/helper"
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.TimedOut: Failed to activate service 'org.rnd2.cpupower_gui.helper': timed out (service_start_timeout=25000ms)
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 154, in apport_excepthook
    os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o640), 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_bin_cpupower-gui.0.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.rnd2.cpupower_gui.helper': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/cpupower-gui", line 40, in <module>
    from cpupower_gui import main
  File "/usr/share/cpupower-gui/cpupower_gui/main.py", line 36, in <module>
    from .window import CpupowerGuiWindow
  File "/usr/share/cpupower-gui/cpupower_gui/window.py", line 26, in <module>
    "org.rnd2.cpupower_gui.helper", "/org/rnd2/cpupower_gui/helper"
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.TimedOut: Failed to activate service 'org.rnd2.cpupower_gui.helper': timed out (service_start_timeout=25000ms)
```

**Comment by TensorTom** [comment]
Problem was the original build was done by meson which was running in a 3.8 virtual env. Reinstalled meson by root system python, recompiled, fixed.
