### ISSUE TITLE
Cannot install it properly (Solved)

### ISSUE THREAD

**Issue by AlfredEVOL** [vagnum08/cpupower-gui#38]
Followed the readme to install..
on ` ninja -C build install ` , i get this:

```
`No such key “show-mount” in schema “org.gnome.shell.extensions.ding:pop” as specified in override file “/usr/share/glib-2.0/schemas/50_pop-session.gschema.override”; ignoring override for this key.`

after this , i tried to open both the gui and throught the terminal, i get this:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 177, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 361, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.rnd2.cpupower_gui.helper': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/cpupower-gui", line 33, in <module>
    from cpupower_gui.helper import (
  File "/usr/share/cpupower-gui/cpupower_gui/helper.py", line 14, in <module>
    SESSION = BUS.get_object(
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 241, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 182, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 277, in start_service_by_name
    return (True, self.call_blocking(BUS_D

```
I use PopOS 20.10 with the mainline 5.9.6 kernel

**Comment by vagnum08** [comment]
There is an issue with the installation using meson.
It doesn't create the required symlink.
Try adding the symlink manually
 `ln -sf /lib/systemd/system/cpupower-gui-helper.service /etc/systemd/system/dbus-org.rnd2.cpupower_gui.helper.service`.

**Comment by AlfredEVOL** [comment]
Didnt work:
`cpupower-gui 
Traceback (most recent call last):
  File "/usr/bin/cpupower-gui", line 367, in <module>
    from cpupower_gui import main
  File "/usr/share/cpupower-gui/cpupower_gui/main.py", line 38, in <module>
    from .window import CpupowerGuiWindow
  File "/usr/share/cpupower-gui/cpupower_gui/window.py", line 23, in <module>
    gi.require_version("Handy", "1")
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available for version %s' %
ValueError: Namespace Handy not available for version 1
`

**Comment by AlfredEVOL** [comment]
cpupower-gui 
Traceback (most recent call last):
  File "/usr/bin/cpupower-gui", line 367, in <module>
    from cpupower_gui import main
  File "/usr/share/cpupower-gui/cpupower_gui/main.py", line 38, in <module>
    from .window import CpupowerGuiWindow
  File "/usr/share/cpupower-gui/cpupower_gui/window.py", line 23, in <module>
    gi.require_version("Handy", "1")
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available for version %s' %
ValueError: Namespace Handy not available for version 1

**Comment by vagnum08** [comment]
It did work. That is a different one. This version has a new dependency, `libhandy`.
If you run `apt install gir1.2-handy-1` it should fix the problem.

**Comment by AlfredEVOL** [comment]
Yeah , it works now...it looks great. ,btw..thanks for the help
![Screenshot from 2020-11-07 07-19-37](https://user-images.githubusercontent.com/57448041/98428932-c759d280-20c9-11eb-903a-21c567aaffbe.png)

**Comment by vagnum08** [comment]
Glad you got it working.

I will leave the issue open for others to see and as a reminder for me till I fix the symlink install.

**Comment by phongvu99** [comment]
> It did work. That is a different one. This version has a new dependency, `libhandy`.
> If you run `apt install gir1.2-handy-1` it should fix the problem.

Hi, I update the app and can't seem to find the missing dependency on my distro. Linux Mint 19.3 Tricia

**Comment by vagnum08** [comment]
I had a quick look. `libhandy` is not available at all on Linux Mint.
I might try adding `libhandy` as a subproject so if it is not installed it would be built along with `cpupower-gui`
