### ISSUE TITLE
[Fedora 33] Bad dependecy with the opensuse build

### ISSUE THREAD

**Issue by OnikenX** [vagnum08/cpupower-gui#42]
In fedora 33 the package asking for pyxdg while i do have python3-pyxdg installed.

**Setup (please complete the following information):**
 - Distro: Fedora 33
 - Package version: 0.9.1-1.9
 - Installed via: https://software.opensuse.org/download.html?project=home%3Aerigas%3Acpupower-gui&package=cpupower-gui

**Additional context**
Specifying the python version with python3-pyxdg or python2-pyxdg could help.

**Comment by vagnum08** [comment]
Thanks for letting me know. i will sort it out soon and upgrade to 1.0.0.

**Comment by bwiercinski** [comment]
+1

**Comment by vagnum08** [comment]
Sorry for taking this long, but it is in my plans for tomorrow.

**Comment by vagnum08** [comment]
I have updated the dependency and got the same error as in #39 with Fedora 32.
I am going to sort out the dependencies for version 1.0.0.

**Comment by vagnum08** [comment]
I have updated the packages on OBS to 1.0.0. I am testing it currently.
Feel free to try it and let me know.

**Comment by bwiercinski** [comment]
i was able to install but i'm getting
```
Traceback (most recent call last):
  File "/usr/lib64/python3.9/site-packages/dbus/bus.py", line 177, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib64/python3.9/site-packages/dbus/bus.py", line 361, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib64/python3.9/site-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: The name does not have an owner

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/cpupower-gui", line 33, in <module>
    from cpupower_gui.helper import (
  File "/usr/share/cpupower-gui/cpupower_gui/helper.py", line 14, in <module>
    SESSION = BUS.get_object(
  File "/usr/lib64/python3.9/site-packages/dbus/bus.py", line 241, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
  File "/usr/lib64/python3.9/site-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib64/python3.9/site-packages/dbus/bus.py", line 182, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib64/python3.9/site-packages/dbus/bus.py", line 277, in start_service_by_name
    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib64/python3.9/site-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: Could not activate remote peer.
```

br

**Comment by vagnum08** [comment]
Hi, I have sorted this issue in the latest version of the package on OBS.

The systemd/dbus service was not enabled by default on Fedora during install.
