### ISSUE TITLE
Application Fails To Launch After Updating

### ISSUE THREAD

**Issue by intelligentgaming** [vagnum08/cpupower-gui#46]
Hi there, I used Kubuntu 20.10 and installed CPUPower-GUI from the repositories and the application worked fine. 

However after updating to a newer version it no longer launches, so I removed / purged the newer version and reinstalled the version from the 20.10 repositories but now the application does not want to load at all and spits out the following message in the Terminal.

ryan@RYAN-PC:~$ cpupower-gui
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 177, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 361, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.rnd2.cpupower_gui.helper': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/cpupower-gui", line 40, in <module>
    from cpupower_gui import main
  File "/usr/share/cpupower-gui/cpupower_gui/main.py", line 36, in <module>
    from .window import CpupowerGuiWindow
  File "/usr/share/cpupower-gui/cpupower_gui/window.py", line 25, in <module>
    SESSION = BUS.get_object(
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 241, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 182, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 277, in start_service_by_name
    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.systemd1.UnitMasked: Unit cpupower-gui-helper.service is masked.
ryan@RYAN-PC:~$ 

Any ideas?

**Comment by intelligentgaming** [comment]
Would running without the quotes "systemctl unmask cpupower-gui-helper.service" fix it?

**Comment by vagnum08** [comment]
That's what I was going to suggest.

**Comment by intelligentgaming** [comment]
> That's what I was going to suggest.

Alright, I'll give it a go tonight.

**Comment by intelligentgaming** [comment]
That did the trick, thanks.
