### ISSUE TITLE
Settings not init at runtime

### ISSUE THREAD

**Issue by tallero** [vagnum08/cpupower-gui#48]
I do get 

```python
Traceback (most recent call last):
  File "/usr/share/cpupower-gui/cpupower_gui/main.py", line 76, in do_activate
    win = CpupowerGuiWindow(application=self)
  File "/usr/share/cpupower-gui/cpupower_gui/window.py", line 177, in __init__
    self.load_cpu_settings()
  File "/usr/share/cpupower-gui/cpupower_gui/window.py", line 207, in load_cpu_settings
    self.energy_pref_avail = self.settings[0].energy_pref_avail
KeyError: 0
```

when running the program. Starting from desktop file also does not work.

- version: `1.0.0`
- distro: arch

**Comment by vagnum08** [comment]
Energy preferences are only available on Intel based hardware. What kind of system do you have (processor info)?

**Comment by tallero** [comment]
i7 930

**Comment by vagnum08** [comment]
Sorry for the late response, I didn't have an Intel system at hand.

Could you check if you have a file called `energy_performance_available_preferences` in `/sys/devices/system/cpu/cpu0/cpufreq/`.

**Comment by supdrewin** [comment]
The required feature depends on `intel_pstate`, but it's only available for Sandy Bridge and later generations of Intel processors. It seems that `i7 930` is not supported.

**Comment by vagnum08** [comment]
It should catch the error and handle it properly. I will try to patch it soon.
