### ISSUE TITLE
[Linux Mint 20.2] cpupower-gui 1.0.0 fails to start

### ISSUE THREAD

**Issue by GingkathFox** [vagnum08/cpupower-gui#51]
**Describe the bug**
the GUI fails to start, some issue about Handy.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install from the build repo.
2. start the app.
4. See error:
```
Traceback (most recent call last):
  File "/usr/bin/cpupower-gui", line 367, in <module>
    from cpupower_gui import main
  File "/usr/share/cpupower-gui/cpupower_gui/main.py", line 38, in <module>
    from .window import CpupowerGuiWindow
  File "/usr/share/cpupower-gui/cpupower_gui/window.py", line 23, in <module>
    gi.require_version("Handy", "1")
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 132, in require_version
    raise ValueError('Namespace %s not available for version %s' %
ValueError: Namespace Handy not available for version 1
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_bin_cpupower-gui.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/cpupower-gui", line 367, in <module>
    from cpupower_gui import main
  File "/usr/share/cpupower-gui/cpupower_gui/main.py", line 38, in <module>
    from .window import CpupowerGuiWindow
  File "/usr/share/cpupower-gui/cpupower_gui/window.py", line 23, in <module>
    gi.require_version("Handy", "1")
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 132, in require_version
    raise ValueError('Namespace %s not available for version %s' %
ValueError: Namespace Handy not available for version 1
```

**Expected behaviour**
App starts.

**Setup (please complete the following information):**
 - Distro:Linux Mint 20.2
 - Package version: 1.0.0
 - Installed via: package

**Comment by kelebek333** [comment]
Try to download and install following packages.

http://archive.ubuntu.com/ubuntu/pool/main/libh/libhandy-1/gir1.2-handy-1_1.0.0-2_amd64.deb
http://archive.ubuntu.com/ubuntu/pool/main/libh/libhandy-1/libhandy-1-0_1.0.0-2_amd64.deb

**Comment by GingkathFox** [comment]
I actually switched to Endeavour for unrelated reasons, so i might as well close this. I couldnt find gir1.2 when i searched, howd you find it?
