### ISSUE TITLE
Unable To Launch Version 1.0.0

### ISSUE THREAD

**Issue by intelligentgaming** [vagnum08/cpupower-gui#63]
Hi there.

Version 1.0.0 has been installed on my system for a while (Kubuntu 21.04) but when I attempted to launch it today it did not work.

So I launched it through the Terminal and got the following output. 

Traceback (most recent call last):
  File "/usr/bin/cpupower-gui", line 367, in <module>
    from cpupower_gui import main
  File "/usr/share/cpupower-gui/cpupower_gui/main.py", line 38, in <module>
    from .window import CpupowerGuiWindow
  File "/usr/share/cpupower-gui/cpupower_gui/window.py", line 23, in <module>
    gi.require_version("Handy", "1")
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available for version %s' %
ValueError: Namespace Handy not available for version 1

I've reinstalled it, and have not resolved this issue. 

Any ideas?

**Comment by supdrewin** [comment]
I check the the package list from ubuntu site, and the handy version is 0, not the required version 1.

**Comment by intelligentgaming** [comment]
Both libhandy-1-0 and libhandy-0.0-0 are installed.
