### ISSUE TITLE
It won't compile in Debian stable (bullseye)

### ISSUE THREAD

**Issue by Fibroblasto** [vagnum08/cpupower-gui#70]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

It won't compile in Debian stable (bullseye):

> meson.build:1:0: ERROR: Meson version is 0.56.2 but project requires >= 0.58.0

The openSUSE builds don't work. This is the error:

> Traceback (most recent call last):
  File "/usr/bin/cpupower-gui", line 367, in <module>
    from cpupower_gui import main
  File "/usr/share/cpupower-gui/cpupower_gui/main.py", line 38, in <module>
    from .window import CpupowerGuiWindow
  File "/usr/share/cpupower-gui/cpupower_gui/window.py", line 23, in <module>
    gi.require_version("Handy", "1")
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Handy not available

It would be great it were possible to install it in Debian bullseye.

**Comment by vagnum08** [comment]
For the opensuse build the error is that you don't have libhandy-1 installed.
Run `sudo apt-get install gir1.2-handy-1 libhandy-1-0` to install the gobject introspection module for libhandy-1.

As for the meson issue I will backport the changes for Debian bullseye.
