### ISSUE TITLE
TypeError: 'float' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by ryanmusante** [vagnum08/cpupower-gui#86]
**TypeError: 'float' object cannot be interpreted as an integer**

Steps to reproduce the behaviour:
1. sudo cpupower-gui freq --min 2300 --max 2300 0-15
```

Setting CPU0 frequency...
ERROR:dbus.connection:Unable to set arguments (0, 2300000.0, 2300000) according to signature 'iii': <class 'TypeError'>: 'float' object cannot be interpreted as an integer
Traceback (most recent call last):
  File "/usr/bin/cpupower-gui", line 351, in <module>
    args.func(args)
  File "/usr/bin/cpupower-gui", line 222, in set_freqs
    set_cpu_min_freq(core, args.min)
  File "/usr/share/cpupower-gui/cpupower_gui/helper.py", line 175, in set_cpu_min_freq
    HELPER.update_cpu_settings(cpu, freq, fmax)
  File "/usr/lib/python3.10/site-packages/dbus/proxies.py", line 72, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3.10/site-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File "/usr/lib/python3.10/site-packages/dbus/connection.py", line 643, in call_blocking
    message.append(signature=signature, *args)
TypeError: 'float' object cannot be interpreted as an integer
```
OS: Manjaro 21.3.1 Ruah
Kernel: x86_64 Linux 5.18.8-262-tkg-pds
CPU: 11th Gen Intel Core i7-11800H @ 16x 2.3GHz [47.0°C]
GPU: NVIDIA GeForce RTX 3080 Laptop GPU
RAM: 7897MiB / 64089MiB

**Comment by vagnum08** [comment]
That is weird.

`ERROR:dbus.connection:Unable to set arguments (0, 2300000.0, 2300000) according to signature 'iii': <class 'TypeError'>:` 

As you can see the second argument (min frequency) is a float, however the third argument is an integer as expected.

The question is why `--min 2300` is converted to a float, whereas `--max 2300` isn't.

**Comment by vagnum08** [comment]
Had a look on the relevant code.

**Comment by vagnum08** [comment]
Luckily I have both 3.9 and 3.10 installed on my computer.

```bash
❯ python3.9 /usr/bin/cpupower-gui freq --min 2300 0-3
Setting CPU0 frequency...
OK
CPU0:
	Freqs (MHz): (2300.0, 2300.0), Limits: (400.0, 2300.0)
Setting CPU1 frequency...
OK
CPU1:
	Freqs (MHz): (2300.0, 2300.0), Limits: (400.0, 2300.0)
Setting CPU2 frequency...
OK
CPU2:
	Freqs (MHz): (2300.0, 2300.0), Limits: (400.0, 2300.0)
Setting CPU3 frequency...
OK
CPU3:
	Freqs (MHz): (2300.0, 2300.0), Limits: (400.0, 2300.0)

```

```bash
❯ python3.10 /usr/bin/cpupower-gui freq --min 2300 0-3
Setting CPU0 frequency...
ERROR:dbus.connection:Unable to set arguments (0, 2300000.0, 2300000) according to signature 'iii': <class 'TypeError'>: 'float' object cannot be interpreted as an integer
Traceback (most recent call last):
  File "/usr/bin/cpupower-gui", line 351, in <module>
    args.func(args)
  File "/usr/bin/cpupower-gui", line 222, in set_freqs
    set_cpu_min_freq(core, args.min)
  File "/usr/share/cpupower-gui/cpupower_gui/helper.py", line 175, in set_cpu_min_freq
    HELPER.update_cpu_settings(cpu, freq, fmax)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 72, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 643, in call_blocking
    message.append(signature=signature, *args)
TypeError: 'float' object cannot be interpreted as an integer
```
Testing further though, `freq *=1e3` turns `freq` into a float on both versions. `dbus` is the same version (1.2.18) on both py3.9 and py3.10.

**Comment by vagnum08** [comment]
No matter what is going on in there the solution is simple.

Line 178 and 197 should be changed to `freq = int(freq * 1e3)` so that `freq` stays an integer.
After this change we get: 

```bash
❯ python3.10 /usr/bin/cpupower-gui freq --min 2300 0-3
Setting CPU0 frequency...
OK
CPU0:
	Freqs (MHz): (2300.0, 2300.0), Limits: (400.0, 2300.0)
Setting CPU1 frequency...
OK
CPU1:
	Freqs (MHz): (2300.0, 2300.0), Limits: (400.0, 2300.0)
Setting CPU2 frequency...
OK
CPU2:
	Freqs (MHz): (2300.0, 2300.0), Limits: (400.0, 2300.0)
Setting CPU3 frequency...
OK
CPU3:
	Freqs (MHz): (2300.0, 2300.0), Limits: (400.0, 2300.0)

```
