### ISSUE TITLE
Does not start on last ArchLinux

### ISSUE THREAD

**Issue by MarcoRoccagliSigma** [vagnum08/cpupower-gui#92]
Hello there, i've compiled the source from github, but it does not start at all.
By starting from terminal, after some time this is displayed:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/dbus/bus.py", line 177, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3.10/site-packages/dbus/bus.py", line 361, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3.10/site-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.rnd2.cpupower_gui.helper': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/cpupower-gui", line 33, in <module>
    from cpupower_gui.helper import (
  File "/usr/local/share/cpupower-gui/cpupower_gui/helper.py", line 14, in <module>
    SESSION = BUS.get_object(
  File "/usr/lib/python3.10/site-packages/dbus/bus.py", line 241, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
  File "/usr/lib/python3.10/site-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3.10/site-packages/dbus/bus.py", line 182, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3.10/site-packages/dbus/bus.py", line 277, in start_service_by_name
    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3.10/site-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.TimedOut: Failed to activate service 'org.rnd2.cpupower_gui.helper': timed out (service_start_timeot=25000ms)

Using last Arch with kernel 6.0.7-arch1-1 in Gnome DE.
Any clues for this?

Thanks

**Comment by vagnum08** [comment]
I think you are getting the error because the helper utility service is not running.

You have to enable the helper service with systemctl.

**Comment by MarcoRoccagliSigma** [comment]
Thanks i solved by installed directly from AUR
