### ISSUE TITLE
Fedrora 36: Install bricks system

### ISSUE THREAD

**Issue by LeSnake04** [vagnum08/cpupower-gui#96]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Build master with `mason build`
2. install with `ninja -C build install`

**Expected behaviour**

**Setup (please complete the following information):**
 - Distro: [e.g. Arch, Debian, etc]
 fedora 36
 - Package version: [e.g. 0.7.0]
 master
 - Installed via: [package or source]
source

**Additional context**
uninstalling in rescue boot with `ninja -C build uninstall` fixes it

**Comment by vagnum08** [comment]
There is package for Fedora 36 here: https://software.opensuse.org//download.html?project=multimedia%3Aproaudio&package=cpupower-gui

I didn't have time to test it yet.

**Comment by LeSnake04** [comment]
it failed to install: 
`  file /usr/share/polkit-1/rules.d from install of cpupower-gui-1.0.0-2.1.noarch conflicts with file from package polkit-0.120-5.fc36.x86_64`

**Comment by vagnum08** [comment]
This failure was due to the new packaging. I checked the source `.spec` file that generates that package.
I am currently reuploading the old package source to the old repo.

**Comment by careca1970** [comment]
Hi!
Yes, I also still have problems with installing the RPM package at Fedora.
Same message as @LeSnake04 gets.

Thanks for all efforts!

**Comment by edogawa23** [comment]
please test and report if this test packagee works, I can't currently find the time to try in a virtualbox guest:
https://software.opensuse.org//download.html?project=home%3Aedogawa&package=cpupower-gui

**Comment by LeSnake04** [comment]
It failed:
Running transaction
Preparing : 1/1
Running scriptlet: cpupower-gui-1.0.0+git.20.96b231b-3.1.noarch 1/1
/var/tmp/rpm-tmp.FmbzGU: line 1: fg: no job control
/var/tmp/rpm-tmp.FmbzGU: line 2: fg: no job control
error: %prein(cpupower-gui-1.0.0+git.20.96b231b-3.1.noarch) scriptlet
failed, exit status 1

**Comment by edogawa23** [comment]
Yeah I've managed to install a Fedora 37 guest and see that here too.
The systemd macros used for openSUSE don't fit Fedora it seems.
I'm on it but it will take me a while.

**Comment by edogawa23** [comment]
I think you can try the current package again, release 6.1 was good to install.
The systemd services get installed and started, but the program crashes at launch with a python backtrace I couldn't make sense of in the short time available to me this morning.

**Comment by edogawa23** [comment]
here it is:

(cpupower-gui:2231): Handy-CRITICAL **: 01:06:24.874: hdy_combo_row_set_selected_index: assertion 'selected_index == -1 || (priv->bound_model != NULL && selected_index < g_list_model_get_n_items (priv->bound_model))' failed
Traceback (most recent call last):
  File "/usr/share/cpupower-gui/cpupower_gui/main.py", line 76, in do_activate
    win = CpupowerGuiWindow(application=self)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/cpupower-gui/cpupower_gui/window.py", line 178, in __init__
    self.load_cpu_settings()
  File "/usr/share/cpupower-gui/cpupower_gui/window.py", line 208, in load_cpu_settings
    self.energy_pref_avail = self.settings[0].energy_pref_avail
                             ~~~~~~~~~~~~~^^^
KeyError: 0

**Comment by vagnum08** [comment]
It is a bug. It tries to read energy preferences (intel p-power features) but the settings dict is empty. I should have used `get` instead of indexing it directly.

I will fix this up.
